apiVersion: v1
kind: Service
metadata:
  name: identityservice-service
  namespace: api-gateway-namespace
spec:
  selector:
    app: identityservice
  ports:
    - protocol: TCP
      port: 7101
      targetPort: 7101
  type: ClusterIP