apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocelotapigateway
  namespace: api-gateway-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocelotapigateway
  template:
    metadata:
      labels:
        app: ocelotapigateway
    spec:
      containers:
      - name: ocelotapigateway
        image: ocelotapigateway:latest
        ports:
          - containerPort: 7100
        readinessProbe:
          httpGet:
            path: /healthz
            port: 7100
          initialDelaySeconds: 5
          periodSeconds: 10