apiVersion: v1
kind: Service
metadata:
  name: ocelotapigateway-service
  namespace: api-gateway-namespace
spec:
  selector:
    app: ocelotapigateway
  ports:
    - protocol: TCP
      port: 7100
      targetPort: 7100
  type: ClusterIP