apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocelot-api-gateway
  namespace: api-gateway-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocelot-api-gateway
  template:
    metadata:
      labels:
        app: ocelot-api-gateway
    spec:
      containers:
      - name: ocelot-api-gateway
        image: ocelotapigateway:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ocelot-api-gateway
  namespace: api-gateway-namespace
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: ocelot-api-gateway