apiVersion: v1
kind: Service
metadata:
  name: authservice-service
  namespace: api-gateway-namespace
spec:
  selector:
    app: authservice
  ports:
    - protocol: TCP
      port: 7102
      targetPort: 7102
  type: ClusterIP